"""Add metadata to media.

Revision ID: c434a5920104
Revises: 02bc5fd54e77
Create Date: 2016-03-25 11:14:59.791090

"""

# revision identifiers, used by Alembic.
revision = 'c434a5920104'
down_revision = '02bc5fd54e77'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('props', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'props')
    ### end Alembic commands ###
